adapters:
#  - reverse-ws
 - http

enableVerify: true
verifyKey: 1234567890

debug: false

singleMode: false

cacheSize: 4096

adapterSettings:
  http:
      ## http server 监听的本地地址
      ## 一般为 localhost 即可, 如果多网卡等情况，自定设置
      host: 192.168.50.198

      ## http server 监听的端口
      ## 与 websocket server 可以重复, 由于协议与路径不同, 不会产生冲突
      port: 8080

      ## 配置跨域, 默认允许来自所有域名
      cors: [*]

      ## 未读队列最大容量，为 0 时不接收任何消息
      unreadQueueMaxSize: 100
      
  # reverse-ws:
  #   ## 远端 websocket server 地址配置
  #   destinations:
  #   - host: 107.172.155.65
  #     port: 18854
  #     path: /
  #     protocol: ws